{% set name = "english" %}
{% set version = "2020.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/english-{{ version }}.tar.gz
  sha256: 7105ed1e9d22b0bd9c1841e7275d3e6e83a34cee475a7e291f70a05721732080

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - six

test:
  imports:
    - english
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/technige/english
  summary: English language utility library for Python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marimeireles
